### ISSUE TITLE
Making this simpler

### ISSUE THREAD

**Issue by spookyuser** [estallio/sanity-plugin-cloudflare-pages-deploy#2]
Soo, I really want to use this but I think setting up a proxy for api requests is kinda a lot just to trigger builds, wouldn't it be possible just to send a get request to the webhooks link in a cloudflare pages project and achieve 90% of the functionality here? Would you be interested in me taking a crack at adding this as an option for users that don't want to setup the proxy?

**Comment by estallio** [comment]
Sorry for the late answer. Maybe you already found the solution. However, Sanity already supports hooks on their management dashboard like:
![Github-Help](https://user-images.githubusercontent.com/26573555/191016476-a912d4ce-dbda-428f-981f-72545bcff365.jpg)
